import test from "node:test";
import assert from "node:assert/strict";
import { demoState,stateSchema } from "../lib/balance.ts";
import { importSchema } from "../lib/library.ts";
test("old saved records receive empty question and attempt lists",()=>{const old=demoState("2026-09-23");delete old.questions;delete old.attempts;const parsed=stateSchema.parse(old);assert.deepEqual(parsed.questions,[]);assert.deepEqual(parsed.attempts,[])});
test("question imports reject invalid answer index and excessive batches",()=>{const q={prompt:"Question",options:["A","B"],correctIndex:0};assert.equal(importSchema.safeParse([q]).success,true);assert.equal(importSchema.safeParse([{...q,correctIndex:2}]).success,false);assert.equal(importSchema.safeParse(Array(201).fill(q)).success,false)});
test("attempts must reference a question and match the selected answer",()=>{const s=demoState("2026-09-23");s.questions=[{id:"q",courseId:s.courses[0].id,prompt:"Q",options:["A","B"],correctIndex:0,source:"",explanation:""}];s.attempts=[{id:"a",questionId:"q",date:"2026-09-23",selected:1,correct:true}];assert.equal(stateSchema.safeParse(s).success,false);s.attempts[0].correct=false;assert.equal(stateSchema.safeParse(s).success,true);s.attempts[0].questionId="missing";assert.equal(stateSchema.safeParse(s).success,false)});
test("records saved before knowledge points keep working and get empty defaults",()=>{const old=demoState("2026-09-23");delete old.knowledgePoints;old.questions=[{id:"q",courseId:old.courses[0].id,prompt:"Q",options:["A","B"],correctIndex:0,explanation:"",source:""}];const parsed=stateSchema.parse(old);assert.deepEqual(parsed.knowledgePoints,[]);assert.equal(parsed.gaps[0].knowledgePointId,"");assert.equal(parsed.questions[0].knowledgePointId,"");assert.equal(parsed.questions[0].materialId,"");assert.equal(parsed.knowledgePoints.length,0)});
test("knowledge points must belong to a course and question links must resolve",()=>{const s=demoState("2026-09-23"),course=s.courses[0].id;s.knowledgePoints=[{id:"kp",courseId:course,label:"每搏输出量的影响因素",detail:"",materialId:"",locator:"第 12 页",status:"accepted",createdAt:"2026-09-23"}];s.questions=[{id:"q",courseId:course,prompt:"Q",options:["A","B"],correctIndex:0,explanation:"",source:"",knowledgePointId:"kp",materialId:""}];assert.equal(stateSchema.safeParse(s).success,true);s.questions[0].knowledgePointId="missing";assert.equal(stateSchema.safeParse(s).success,false);s.questions[0].knowledgePointId="";s.knowledgePoints[0].courseId="missing";assert.equal(stateSchema.safeParse(s).success,false);s.knowledgePoints[0].courseId=course;s.knowledgePoints.push({...s.knowledgePoints[0]});assert.equal(stateSchema.safeParse(s).success,false)});
