"use client";
import LibraryPanel from "./library-panel";
import CoachPanel,{ type ExplainSeed } from "./coach-panel";
import ExplainDialog from "./explain-dialog";
import { useEffect,useRef,useState } from "react";
import { Activity,ArrowUpRight,BookOpen,Check,Clock,Plus,Moon,Settings2,Pause,Play,RotateCcw,Heart,ChevronRight,AlertCircle,GraduationCap,FileText,MoreHorizontal } from "lucide-react";
import { Tabs,TabsList,TabsTrigger,TabsContent } from "@/components/ui/tabs";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Progress } from "@/components/ui/progress";
import { Skeleton } from "@/components/ui/skeleton";
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription } from "@/components/ui/empty";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";
import { today,weekOf,addDays,daysUntil,newId,blankState,demoState,dayState,weekState,getMode,modeNames,masteryNames,reviewDone,courseTarget,recommend,stateSchema,type State,type Action,type Mode } from "@/lib/balance";

type Modal={kind:string;id?:string;action?:Action;type?:string};
type Values=Record<string,string|boolean>;
type Field={key:string;label:string;type?:"textarea"|"number"|"date"|"switch";value?:string|number|boolean;required?:boolean;min?:number;max?:number;step?:number;options?:[string,string][];hint?:string};
const modes:[string,string][]=[["auto","自动判断"],["normal","正常周"],["busy","忙周"],["exam","考试周"]];
const classNames={A:"值得听",B:"听不懂",C:"低价值"};
const classInstructions={A:"抓住机制和因果链。先听懂，再记关键词。",B:"写下“为什么 X 导致 Y”，记住卡点后继续跟课。",C:"切换到本课框架、旧卡片或短作业，仍留意重点与课程要求。"};
const nav=[["today","今日"],["coach","学习教练"],["courses","课程"],["assignments","作业"],["library","资料与题库"],["life","生活与发展"],["week","每周复盘"]];
const mobileNav=[{id:"today",label:"今日",Icon:Clock},{id:"coach",label:"教练",Icon:GraduationCap},{id:"courses",label:"课程",Icon:BookOpen},{id:"library",label:"资料",Icon:FileText}] as const;
const mobileMoreNav:[[string,string],[string,string],[string,string]]=[["assignments","作业"],["life","生活与发展"],["week","每周复盘"]];
function Pick({label,value,options,onChange}:{label:string;value:string;options:[string,string][];onChange:(v:string)=>void}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="pick"><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,n])=><SelectItem key={v} value={v}>{n}</SelectItem>)}</SelectContent></Select>}
function EmptyBox({title,description,children}:{title:string;description:string;children?:React.ReactNode}){return <Empty className="empty-box"><EmptyHeader><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader>{children}</Empty>}
function FormFields({fields,values,setValues}:{fields:Field[];values:Values;setValues:(v:Values)=>void}){return <div className="form-fields">{fields.map(f=><div className={"field "+(f.type==="switch"?"switch-field":"")} key={f.key}><label htmlFor={"field-"+f.key}>{f.label}{f.required?<span className="required"> *</span>:null}</label>{f.options?<Pick label={f.label} value={String(values[f.key]??f.value??f.options[0][0])} options={f.options} onChange={v=>setValues({...values,[f.key]:v})}/>:f.type==="switch"?<Switch id={"field-"+f.key} checked={Boolean(values[f.key]??f.value)} onCheckedChange={v=>setValues({...values,[f.key]:v})}/>:f.type==="textarea"?<textarea id={"field-"+f.key} required={f.required} maxLength={4000} rows={3} value={String(values[f.key]??f.value??"")} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>:<input id={"field-"+f.key} required={f.required} type={f.type??"text"} min={f.min} max={f.max} step={f.step??1} maxLength={f.type?80:300} value={String(values[f.key]??f.value??"")} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>} {f.hint&&<small>{f.hint}</small>}</div>)}</div>}
export default function BalanceApp(){
 const [data,setData]=useState<State|null>(null),[demo,setDemo]=useState(false),[revision,setRevision]=useState(0),[error,setError]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[needsAuth,setNeedsAuth]=useState(false);
 const [date,setDate]=useState(today()),[tab,setTab]=useState("today"),[modal,setModal]=useState<Modal|null>(null),[values,setValues]=useState<Values>({}),[active,setActive]=useState<{action:Action;started:number}|null>(null),[elapsed,setElapsed]=useState(0),[explain,setExplain]=useState<ExplainSeed|null>(null);
 const pending=useRef(false);const live=useRef({data,demo,revision});live.current={data,demo,revision};
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/state",{cache:"no-store",signal:AbortSignal.timeout(15000)}),j=await r.json() as {state:State|null;revision:number;error?:string};if(!r.ok){setNeedsAuth(r.status===401);throw Error(j.error)}setRevision(j.revision);setDemo(!j.state);setData(j.state?stateSchema.parse(j.state):demoState(today()));setNeedsAuth(false)}catch(e){setError(e instanceof Error&&e.name==="TimeoutError"?"读取超时，请检查网络后重试。":e instanceof Error?e.message:"读取失败，请重试。")}finally{setLoading(false)}}
 useEffect(()=>{void load();const t=setInterval(()=>setDate(today()),60000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(!active)return;const t=setInterval(()=>setElapsed(Math.floor((Date.now()-active.started)/1000)),1000);return()=>clearInterval(t)},[active]);
 async function save(next:State,message="已保存",force=false){
 if(pending.current)return false;
 const parsed=stateSchema.safeParse(next);if(!parsed.success){toast.error(parsed.error.issues[0]?.message||"请检查输入");return false}
 pending.current=true;setSaving(true);setError("");
 try{if(live.current.demo&&!force){setData(next);toast.success(message+" · 示例体验");return true}
 const r=await fetch("/api/state",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({revision:live.current.revision,state:next})}),j=await r.json() as {revision:number;error?:string};if(!r.ok)throw Error(j.error||"保存失败");
 setRevision(j.revision);setData(next);setDemo(false);toast.success(message);return true;
 }catch(e){setError(e instanceof Error?e.message:"保存失败，请重试");return false}finally{pending.current=false;setSaving(false)}
 }
 function edit(fn:(s:State)=>void,message?:string){const s=structuredClone(live.current.data!);fn(s);return save(s,message)}
 function open(m:Modal,initial:Values={}){setValues(initial);setModal(m)}
 function putDay(s:State){s.days[date]??=dayState(s,date);return s.days[date]}
 async function startOwn(){if(await save(blankState(),"已建立你的一周",true)){setTab("courses");open({kind:"course"})}}
 function startAction(a:Action){setActive({action:a,started:Date.now()});setElapsed(0);if(a.kind==="closure"){open({kind:"closure",id:a.sourceId,action:a})}}
 function logAction(a:Action){if(a.kind==="closure")open({kind:"closure",id:a.sourceId,action:a});if(a.kind==="review")open({kind:"review",id:a.sourceId,action:a});if(a.kind==="assignment")open({kind:"worklog",id:a.sourceId,action:a});if(a.kind==="rest"||a.kind==="development")open({kind:"life",id:a.sourceId,type:a.kind==="rest"?"rest":"development",action:a})}
 useEffect(()=>{
 const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context)return;
 const lifecycle=new AbortController();
 const defs=[{name:"read_today_actions",title:"查看今日建议",description:"读取今日最多三个行动及推荐原因，不修改记录。",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){if(!input||typeof input!=="object"||Object.keys(input).length)throw Error("输入必须为空对象");if(!live.current.data)throw Error("记录尚未加载");return recommend(live.current.data,today())}},
 {name:"open_balance_module",title:"打开学习生活模块",description:"切换到指定页面，不创建或完成记录。",inputSchema:{type:"object",properties:{module:{type:"string",enum:nav.map(x=>x[0])}},required:["module"],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:unknown){const v=input as {module?:string};if(!v||Object.keys(v).length!==1||!nav.some(x=>x[0]===v.module))throw Error("未知模块");setTab(v.module!);return {opened:v.module}}}];
 for(const tool of defs)try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}
 return()=>lifecycle.abort();
 },[]);
 if(loading)return <div className="workspace"><div className="brand"><span className="brand-mark"><Activity/></span><strong>余量</strong></div><div className="loading-stack"><Skeleton className="h-12 w-72"/><Skeleton className="h-72 w-full"/><p>正在取回你的记录…</p></div></div>;
 if(!data)return <main className="workspace"><h1>余量</h1><div className="error-banner">{error}</div>{needsAuth?<a className="btn" href="/signin-with-chatgpt?return_to=/" target="_top">登录并进入我的一周</a>:<button className="btn" onClick={load}>重新加载</button>}</main>;
 const s=data,day=dayState(s,date),week=weekState(s,date),rec=recommend(s,date),wk=weekOf(date),weekDays=Array.from({length:7},(_,i)=>addDays(wk,i));
 const cname=(id:string)=>s.courses.find(c=>c.id===id)?.name??"其他";
 const lifeCount=(type:string)=>new Set(s.life.filter(x=>x.type===type&&weekOf(x.date)===wk).map(x=>x.date)).size;
 const weekMinutes=s.reviews.filter(r=>r.week===wk).reduce((n,r)=>n+r.minutes,0);
 const courseOpts=s.courses.map(c=>[c.id,c.name] as [string,string]);
 const fields:Field[]=[];
 let modalTitle="",description="",submitLabel="保存";
 if(modal?.kind==="course"){const c=s.courses.find(c=>c.id===modal.id);modalTitle=c?"编辑课程":"添加课程";description="先填必要信息，考试日期和掌握度可以以后补。";fields.push({key:"name",label:"课程名称",value:c?.name,required:true},{key:"topics",label:"本周进度 / 主题",value:c?.topics},{key:"core",label:"设为核心课",type:"switch",value:c?.core??true},{key:"mastery",label:"目前掌握度",value:String(c?.mastery??-1),options:[["-1","尚不确定"],...masteryNames.map((n,i)=>[String(i),n] as [string,string])]},{key:"examDate",label:"考试日期",type:"date",value:c?.examDate},{key:"weight",label:"考试重要程度（1–5）",type:"number",value:c?.weight??3,min:1,max:5,required:true},{key:"weeklyMinutes",label:"每周固定复习（分钟）",type:"number",value:c?.weeklyMinutes??120,min:15,max:1200,required:true})}
 if(modal?.kind==="day"){modalTitle="今天的状态";description="可用时间是扣除固定课表、通勤、吃饭和睡眠后，今天愿意投入的总时间。";fields.push({key:"free",label:"今日总可用时间（分钟）",type:"number",value:day.free,min:0,max:1440,required:true},{key:"energy",label:"现在的精力",value:day.energy,options:[["high","充足"],["medium","还可以"],["low","比较累"]]},{key:"sleep",label:"昨晚睡眠（小时）",type:"number",value:day.sleep,min:0,max:24,step:.5,required:true})}
 if(modal?.kind==="class"){modalTitle="记录一节课堂";description="先记录主题，进入后可以随时切换 A / B / C 模式。";fields.push({key:"courseId",label:"课程",options:courseOpts,value:modal.id??courseOpts[0]?.[0]},{key:"topic",label:"这节课的主题",required:true},{key:"date",label:"上课日期",type:"date",value:date,required:true});submitLabel="进入课堂"}
 if(modal?.kind==="gap"){const g=s.gaps.find(g=>g.id===modal.id);modalTitle=g?"处理知识卡点":"记一个卡点";description="把“我不会”缩成一个可回答的问题。";fields.push({key:"courseId",label:"课程",options:courseOpts,value:g?.courseId??modal.type??courseOpts[0]?.[0]},{key:"question",label:"我卡在哪里？",type:"textarea",value:g?.question,required:true},{key:"risk",label:"处理优先级",value:g?.risk??"normal",options:[["high","高 · 影响理解 / 考试重点"],["normal","一般"]]},{key:"status",label:"状态",value:g?.status??"open",options:[["open","本周处理"],["exam","明确留到考前"],["resolved","已经解决"]]},{key:"answer",label:"解释 / 下一步",type:"textarea",value:g?.answer})}
 if(modal?.kind==="closure"){const c=s.sessions.find(x=>x.id===modal.id)!;modalTitle=cname(c.courseId)+" · 课后关闭";description=c.topic+"。关闭代表知道自己哪里会、哪里不会。";fields.push({key:"summary",label:"今天讲了什么？",type:"textarea",value:c.summary||c.topic,required:true},{key:"canExplain",label:"我会什么？",type:"textarea",value:c.canExplain,hint:"用自己的话解释一个机制；简版可暂留空。"}, {key:"stuck",label:"我卡在哪里？",type:"textarea",value:c.stuck,hint:"每行一个问题；留空表示暂时没有卡点。"}, {key:"brief",label:"今天只做 2 分钟简版",type:"switch",value:modal.action?.minutes===2},{key:"minutes",label:"本次实际投入（分钟）",type:"number",value:modal.action?.minutes??12,min:1,max:120,required:true});submitLabel="保存关闭记录"}
 if(modal?.kind==="review"){const c=s.courses.find(x=>x.id===modal.id)!;modalTitle=c.name+" · 单科复习";description=rec.mode==="normal"?"框架压缩 → 问题池 → 闭卷回忆 → 长期记忆点":"本周已降级：先保留闭卷回忆和最高风险问题。";fields.push({key:"minutes",label:"本次实际复习（分钟）",type:"number",value:modal.action?.minutes??30,min:1,max:600,required:true},{key:"framework",label:"① 框架压缩",type:"textarea",hint:"一条主题链或几个关键词就够。"}, {key:"problems",label:"② 问题池处理",type:"textarea",hint:s.gaps.filter(g=>g.courseId===c.id&&g.status==="open").slice(0,2).map(g=>g.question).join("；")||"记录最高风险问题及处理结果。"}, {key:"recall",label:"③ 闭卷回忆",type:"textarea",required:true,hint:"合上资料，你能讲出什么？还漏了什么？"},{key:"memory",label:"④ 长期记忆点",type:"textarea",hint:"只留值得反复回顾的少数点，不必凑满 10 条。"});submitLabel="记录本次复习"}
 if(modal?.kind==="assignment"){const a=s.assignments.find(x=>x.id===modal.id);modalTitle=a?"编辑作业":"添加作业";description="时间上限用于提醒重新判断，不代表到点就可以不交。";fields.push({key:"title",label:"作业名称",value:a?.title,required:true},{key:"courseId",label:"所属课程",value:a?.courseId||"none",options:[["none","其他"],...courseOpts]},{key:"grade",label:"作业分级",value:a?.grade??"B",options:[["A","A · 高学习价值"],["B","B · 必交但学习价值低"],["C","C · 机械任务"]]},{key:"due",label:"截止日期",type:"date",value:a?.due??date,required:true},{key:"estimate",label:"预计总耗时（分钟）",type:"number",value:a?.estimate??45,min:1,max:1440,required:true},{key:"cap",label:"每次投入上限（分钟）",type:"number",value:a?.cap??30,min:1,max:1440,required:true},{key:"minimum",label:"最低合格标准",type:"textarea",value:a?.minimum,required:true},{key:"blockedBy",label:"前置作业（先完成它）",value:a?.blockedBy?.[0]??"none",options:[["none","没有前置"],...s.assignments.filter(x=>x.status==="open"&&x.id!==modal.id).map(x=>[x.id,x.title] as [string,string])],hint:"前置没完成时，今天的学习计划不会排它，只提示要先做前置。界面一次设一个，接口支持多个。"})}
 if(modal?.kind==="worklog"){const a=s.assignments.find(x=>x.id===modal.id)!;modalTitle=a.title;description=a.minimum||"按要求完成后，确认实际提交。";fields.push({key:"minutes",label:"本次实际投入（分钟）",type:"number",value:modal.action?.minutes??Math.min(a.cap,30),min:1,max:1440,required:true},{key:"submitted",label:"已经提交",type:"switch",value:false,hint:"只有实际提交后才打开。未提交的作业会继续保留。"});submitLabel="记录进度"}
 if(modal?.kind==="skip"){modalTitle="今天先跳过";description="这不会删除任务，系统会保留你的原因。";fields.push({key:"reason",label:"跳过原因",options:[["没时间","没时间"],["没精力","没精力"],["任务太大","任务太大"],["优先级变化","优先级变化"]],value:"没时间"});submitLabel="今天跳过"}
 if(modal?.kind==="life"){modalTitle=modal.type==="development"?"记录发展事项":"留一点时间给生活";description=modal.action?.minimum??"记录已经完成的投入。";fields.push({key:"type",label:"类型",value:modal.type??"rest",options:[["rest","休息"],["exercise","运动"],["social","社交"],["development","发展事项"]]},{key:"minutes",label:"本次时长（分钟）",type:"number",value:modal.action?.minutes??20,min:1,max:1440,required:true});if((values.type??modal.type)==="development")fields.push({key:"trackId",label:"发展方向",value:modal.id??s.tracks[0]?.id,options:s.tracks.map(t=>[t.id,t.name])});submitLabel="记录完成"}
 if(modal?.kind==="track"){const t=s.tracks.find(x=>x.id===modal.id);modalTitle=t?"调整发展方向":"添加发展方向";description="最多并行一个主方向和一个维护方向；其他方向暂停保留。";fields.push({key:"name",label:"方向名称",value:t?.name,required:true},{key:"role",label:"本周角色",value:t?.role??"paused",options:[["main","主方向"],["maintain","维护方向"],["paused","暂时暂停"]]},{key:"next",label:"下一小步",type:"textarea",value:t?.next,required:true},{key:"weeklyTarget",label:"每周推进次数",type:"number",value:t?.weeklyTarget??2,min:1,max:10,required:true},{key:"minutes",label:"每次建议时长（分钟）",type:"number",value:t?.minutes??30,min:5,max:180,required:true},{key:"hardDeadline",label:"必须处理的截止日期（可留空）",type:"date",value:t?.hardDeadline})}
 if(modal?.kind==="settings"){modalTitle="我的生活底线";description="以下是可修改的个人设置，请按真实情况填写。";fields.push({key:"sleepFloor",label:"睡眠底线（小时）",type:"number",value:s.settings.sleepFloor,min:4,max:12,step:.5,required:true},{key:"weeklyCapacity",label:"每周课外学习容量（分钟）",type:"number",value:s.settings.weeklyCapacity,min:60,max:6000,required:true,hint:"已扣除上课、生活、必要休息和固定安排。"},{key:"examWindow",label:"考前集中复习窗口（天）",type:"number",value:s.settings.examWindow,min:1,max:60,required:true},{key:"exerciseTarget",label:"每周运动目标（天）",type:"number",value:s.settings.exerciseTarget,min:0,max:7,required:true},{key:"socialTarget",label:"每周社交目标（天）",type:"number",value:s.settings.socialTarget,min:0,max:7,required:true},{key:"restMinutes",label:"每天希望保留的休息（分钟）",type:"number",value:s.settings.restMinutes,min:5,max:120,required:true})}
 if(modal?.kind==="reflection"){modalTitle="收好这一周";description="用 15–20 分钟判断哪里失衡，下周只调整最有影响的一点。";fields.push({key:"reflection",label:"本周：哪些课跟上了？哪些作业超时？生活是否被挤压？",type:"textarea",value:week.reflection,required:true},{key:"adjustment",label:"反复跳过的原因 / 下周要调整什么？",type:"textarea",value:week.adjustment,required:true},{key:"risk",label:"下周最大的一项风险",type:"textarea",value:s.weeks[addDays(wk,7)]?.risk??"",required:true},{key:"nextMode",label:"下周模式",value:s.weeks[addDays(wk,7)]?.mode??"auto",options:modes});submitLabel="保存复盘与下周模式"}
 async function submit(e:React.FormEvent){
 e.preventDefault();if(!modal||saving)return;
 const merged:Values={};for(const f of fields)merged[f.key]=values[f.key]??f.value??f.options?.[0]?.[0]??"";
 const str=(key:string)=>String(merged[key]??"").trim(),num=(key:string)=>Number(merged[key]),bool=(key:string)=>Boolean(merged[key]);
 const next=structuredClone(s),d=putDay(next);let msg="已保存";const mid=modal.id??newId();
 if(modal.kind==="course"){const c={id:mid,name:str("name"),topics:str("topics"),core:bool("core"),mastery:num("mastery"),examDate:str("examDate"),weight:num("weight"),weeklyMinutes:num("weeklyMinutes")};if(modal.id)next.courses=next.courses.map(x=>x.id===mid?c:x);else next.courses.push(c);msg="课程已保存"}
 if(modal.kind==="day"){d.free=num("free");d.energy=str("energy") as typeof d.energy;d.sleep=num("sleep");d.sleepRecorded=true;d.doneForDay=false;msg="已按今天状态更新建议"}
 if(modal.kind==="class"){next.sessions.push({id:newId(),courseId:str("courseId"),date:str("date"),topic:str("topic"),mode:"A",modeEvents:[{mode:"A",at:new Date().toISOString()}],status:"open",summary:"",canExplain:"",stuck:""});msg="课堂已记录"}
 if(modal.kind==="gap"){const g={id:mid,courseId:str("courseId"),sessionId:"",question:str("question"),risk:str("risk") as "high"|"normal",status:str("status") as "open"|"exam"|"resolved",answer:str("answer"),created:s.gaps.find(x=>x.id===mid)?.created??date,knowledgePointId:s.gaps.find(x=>x.id===mid)?.knowledgePointId??""};if(modal.id)next.gaps=next.gaps.map(x=>x.id===mid?g:x);else next.gaps.push(g);msg="知识点已保存"}
 if(modal.kind==="closure"){const c=next.sessions.find(x=>x.id===mid)!;if(!bool("brief")&&!str("canExplain")){toast.error("请写下会什么，或选择简版");return}c.summary=str("summary");c.canExplain=str("canExplain");c.stuck=str("stuck");c.status=bool("brief")?"brief":"closed";for(const q of c.stuck.split("\n").map(x=>x.trim()).filter(Boolean))if(!next.gaps.some(g=>g.courseId===c.courseId&&g.question===q))next.gaps.push({id:newId(),courseId:c.courseId,sessionId:c.id,question:q,risk:"normal",status:"open",answer:"",created:date,knowledgePointId:""});d.spent=Math.min(1440,d.spent+num("minutes"));d.completed.push("closure:"+mid);msg=bool("brief")?"简版已保存，周复习时再补全":"本节课已关闭，卡点已进入问题池"}
 if(modal.kind==="review"){next.reviews.push({id:newId(),courseId:mid,week:wk,date,minutes:num("minutes"),framework:str("framework"),problems:str("problems"),recall:str("recall"),memory:str("memory")});d.spent=Math.min(1440,d.spent+num("minutes"));d.completed.push("review:"+mid);msg="复习已计入本周；问题池状态可逐项确认"}
 if(modal.kind==="assignment"){const old=s.assignments.find(x=>x.id===mid);const a={id:mid,courseId:str("courseId")==="none"?"":str("courseId"),title:str("title"),grade:str("grade") as "A"|"B"|"C",due:str("due"),estimate:num("estimate"),cap:num("cap"),minimum:str("minimum"),spent:old?.spent??0,status:old?.status??"open" as const,blockedBy:str("blockedBy")==="none"?[]:[str("blockedBy")]};if(modal.id)next.assignments=next.assignments.map(x=>x.id===mid?a:x);else next.assignments.push(a);msg="作业已保存"}
 if(modal.kind==="worklog"){const a=next.assignments.find(x=>x.id===mid)!;a.spent=Math.min(1440,a.spent+num("minutes"));a.status=bool("submitted")?"done":"open";d.spent=Math.min(1440,d.spent+num("minutes"));if(a.status==="done")d.completed.push("assignment:"+mid);msg=a.status==="done"?"已记录提交":"已记录投入，作业仍保留到提交";if(num("minutes")>=a.cap&&!bool("submitted"))msg+="；已到复判上限，请检查最小提交要求"}
 if(modal.kind==="skip"){d.skips.push({id:modal.action!.id,reason:str("reason")});msg="今天已跳过，任务仍保留"}
 if(modal.kind==="life"){const type=str("type") as State["life"][number]["type"];const trackId=type==="development"?str("trackId"):"";if(type==="development"&&!next.tracks.some(t=>t.id===trackId)){toast.error("先添加一个发展方向");return}next.life.push({id:newId(),date,type,trackId,minutes:num("minutes")});d.spent=Math.min(1440,d.spent+num("minutes"));if(modal.action)d.completed.push(modal.action.id);msg="已记录，这段时间也是今天的一部分"}
 if(modal.kind==="track"){const t={id:mid,name:str("name"),role:str("role") as "main"|"maintain"|"paused",next:str("next"),weeklyTarget:num("weeklyTarget"),minutes:num("minutes"),hardDeadline:str("hardDeadline")};if(next.tracks.some(x=>x.id!==mid&&x.role===t.role&&t.role!=="paused")){toast.error("这个角色已有方向，请先将原方向改为暂停");return}if(modal.id)next.tracks=next.tracks.map(x=>x.id===mid?t:x);else next.tracks.push(t);msg="发展方向已更新"}
 if(modal.kind==="settings"){next.settings={sleepFloor:num("sleepFloor"),weeklyCapacity:num("weeklyCapacity"),examWindow:num("examWindow"),exerciseTarget:num("exerciseTarget"),socialTarget:num("socialTarget"),restMinutes:num("restMinutes")};msg="个人底线已更新"}
 if(modal.kind==="reflection"){next.weeks[wk]={...week,reflection:str("reflection"),adjustment:str("adjustment"),reviewed:true};const nw=addDays(wk,7);next.weeks[nw]={...weekState(next,nw),mode:str("nextMode") as typeof week.mode,risk:str("risk")};msg="复盘已保存，下周模式已设定"}
 if(await save(next,msg)){setModal(null);if(modal.action){setActive(null);setElapsed(0)}}
 }
 const currentFields=<FormFields fields={fields} values={values} setValues={setValues}/>;
 return <><Toaster position="top-center" richColors/><header className="topbar"><a className="brand" href="/"><span className="brand-mark"><Activity size={23}/></span><strong>余量</strong><span>医学学习与生活</span></a><div className="actions"><span className="save-state">{demo?"示例体验":saving?"保存中…":"记录已保存"}</span><button className="icon-btn" aria-label="生活底线与设置" onClick={()=>open({kind:"settings"})}><Settings2 size={20}/></button></div></header>
 <main className="workspace">
 <div className="page-heading"><div><div className="eyebrow">{new Intl.DateTimeFormat("zh-CN",{month:"long",day:"numeric",weekday:"long",timeZone:"Asia/Shanghai"}).format(new Date(date+"T12:00:00+08:00"))} · ONE WEEK AT A TIME</div><h1>{tab==="today"?"今天，留一点余量。":tab==="coach"?"现在该学什么，这里说清楚。":tab==="courses"?"把每门课，慢慢学扎实。":tab==="assignments"?"按时完成，适度投入。":tab==="library"?"资料有去处，复习有依据。":tab==="life"?"生活，也值得被安排。":"这一周，有没有失衡？"}</h1><p>{tab==="today"?"先做好一件重要的事，再给生活留出位置。":tab==="coach"?"按课表、截止时间、考试日期和你的掌握度排计划，每天只推 1–3 件最关键的事。":tab==="courses"?"课内抓主线，课后留线索，每周做一次压缩。":tab==="assignments"?"把时间花在作业真正有价值的部分。":tab==="library"?"PPT、课本和题库，回到同一门课程里。":tab==="life"?"守住恢复，发展方向保持有限并行。":"留下有效的做法，调整一个最大的阻力。"}</p></div><div className="mode-control"><span className="pill">{modeNames[rec.mode]}</span><Pick label="本周模式" value={week.mode} options={modes} onChange={v=>void edit(n=>{n.weeks[wk]={...weekState(n,date),mode:v as typeof week.mode}},"本周模式已切换")}/></div></div>
 {demo&&<div className="notice"><span><strong>正在体验示例</strong> · 这些课程和安排仅作演示，操作不会写入你的正式记录。</span><button className="btn small" disabled={saving} onClick={startOwn}>开始我的一周 <ArrowUpRight size={16}/></button></div>}
 {error&&<div className="error-banner" role="alert">{error} <button className="btn ghost small" onClick={load}>重新加载记录</button></div>}
 {active&&<section className="active-strip"><div><Play size={17}/><strong>{active.action.title}</strong><span>已开始 {Math.floor(elapsed/60)}:{String(elapsed%60).padStart(2,"0")}</span></div><div className="actions">{elapsed>=active.action.minutes*60&&<span>到达建议时长，可以复判了</span>}<button className="btn small" onClick={()=>logAction(active.action)}>记录本次进度</button><button className="btn ghost small" onClick={()=>setActive(null)}>停止计时</button></div></section>}
 <Tabs value={tab} onValueChange={setTab}><TabsList className="main-tabs">{nav.map(([v,n])=><TabsTrigger key={v} value={v}>{n}</TabsTrigger>)}</TabsList>
 <TabsContent value="today"><div className="dashboard-grid"><section><div className="section-title"><h2>今天的关键行动</h2><span>{rec.actions.length} / 3 件 · 随状态调整</span></div>
 {rec.warnings.map((w,i)=><div className="warning" key={i}><AlertCircle size={17}/><span>{w}</span></div>)}
 {rec.actions.length===0?<EmptyBox title={day.doneForDay?"今天到这里就好。":"现在可以留白。"} description={rec.free===0?"今天的时间已经用完。临近截止的冲突仍需主动协调。":"没有需要继续推送的行动；未完成内容可以在对应模块查看。"}><button className="btn ghost" onClick={()=>{if(day.doneForDay)void edit(n=>{putDay(n).doneForDay=false},"已恢复建议");else open({kind:"day"})}}>{day.doneForDay?"重新查看建议":"调整今日状态"}</button></EmptyBox>:rec.actions.map((a,i)=>i===0?<article className="focus-card" key={a.id}><div className="card-top"><span className="label">01 / {a.kind==="rest"?"优先恢复":a.hard?"先守住截止":"主要推进"}</span>{a.kind==="rest"?<Moon size={22}/>:<BookOpen size={22}/>}</div><h2>{a.title}</h2><p>{a.minimum}</p><div className="focus-meta"><span><Clock size={15}/> {a.minutes} 分钟</span><span>{a.reason}</span></div><div className="actions"><button className="btn light" disabled={saving} onClick={()=>startAction(a)}><Play size={16}/>开始这一步</button><button className="text-btn" onClick={()=>open({kind:"skip",action:a})}>今天先跳过</button></div></article>:<article className="simple-row" key={a.id}><span className="index">0{i+1}</span><div><h3>{a.title}</h3><p>{a.minimum}</p><div className="row-reason">{a.reason}</div><div className="actions row-actions"><button className="btn ghost small" onClick={()=>startAction(a)}>开始</button><button className="text-link" onClick={()=>open({kind:"skip",action:a})}>跳过</button></div></div><span className="pill">{a.minutes} 分钟</span></article>)}
 {rec.actions.length>0&&<button className="stop-day" disabled={saving} onClick={()=>void edit(n=>{putDay(n).doneForDay=true},"今天收工，安排已保留")}><Moon size={16}/>今天就到这里</button>}
 {day.skips.length>0&&<details className="history"><summary>今天跳过的 {day.skips.length} 项</summary>{day.skips.map((x,i)=><div className="between" key={i}><span>{x.reason} · {x.id.split(":")[0]==="review"?"单科复习":x.id.split(":")[0]==="rest"?"休息":"今日行动"}</span><button className="text-link" onClick={()=>void edit(n=>{putDay(n).skips=putDay(n).skips.filter(y=>y.id!==x.id)},"已恢复候选")}>恢复</button></div>)}</details>}
 </section><aside><section className="panel"><div className="section-title"><h2>今天的状态</h2><button className="icon-btn" aria-label="调整今日状态" onClick={()=>open({kind:"day"})}><Settings2 size={18}/></button></div><div className="big-number">{rec.free} <span>分钟余量</span></div><p>今日总可用 {day.free} 分钟，已记录 {day.spent} 分钟。</p><div className="rule-line"/><div className="between"><span>现在精力</span><strong>{day.energy==="low"?"比较累":day.energy==="high"?"充足":"还可以"}</strong></div><div className="between"><span>昨晚睡眠</span><strong className={day.sleep<s.settings.sleepFloor?"text-warn":""}>{day.sleepRecorded?day.sleep+" 小时":"未记录"}</strong></div><div className="between"><span>个人睡眠底线</span><strong>{s.settings.sleepFloor} 小时</strong></div><button className="btn soft full" onClick={()=>open({kind:"day"})}>调整状态，重新建议</button></section><section className="note-panel"><span className="eyebrow">{modeNames[rec.mode]} / 本周原则</span><h3>{rec.mode==="normal"?<>按周平衡，<br/>不必每天面面俱到。</>:rec.mode==="busy"?<>缩小任务，<br/>守住最小闭环。</>:<>跟着考试顺序走，<br/>把薄弱点讲清。</>}</h3><p>{rec.reason}</p></section><div className="weekly-mini"><div className="between"><strong>本周复习</strong><span>{weekMinutes} 分钟</span></div><div className="week-dots">{weekDays.map((d,i)=><span key={d} className={(s.reviews.some(r=>r.date===d)?"filled ":"")+(d===date?"current":"")}><small>{"一二三四五六日"[i]}</small><i>{s.reviews.some(r=>r.date===d)?<Check size={13}/>:new Date(d+"T12:00:00").getDate()}</i></span>)}</div></div></aside></div></TabsContent>
 <TabsContent value="courses"><div className="section-title"><h2>我的课程 <span className="count">{s.courses.length}</span></h2><button className="btn" onClick={()=>open({kind:"course"})}><Plus size={16}/>添加课程</button></div>
 {s.courses.length===0?<EmptyBox title="先放进一门核心课" description="只要课程名和每周复习额度，就能开始运行。"><button className="btn" onClick={()=>open({kind:"course"})}>添加第一门课</button></EmptyBox>:<div className="course-grid">{s.courses.map((c,i)=>{const done=reviewDone(s,c.id,date),target=courseTarget(s,c,date);return <article className="course-card" key={c.id}><div className="card-top"><span className={"course-icon color-"+i%3}><BookOpen size={20}/></span><div className="actions"><span className="pill">{c.core?"核心课":"一般课程"}</span><button className="icon-btn" aria-label={"编辑"+c.name} onClick={()=>open({kind:"course",id:c.id})}><Settings2 size={17}/></button></div></div><h2>{c.name}</h2><p>{c.topics||"还没填写本周进度"}</p><div className="between"><span>掌握度</span><strong>{c.mastery<0?"尚不确定":masteryNames[c.mastery]}</strong></div><div className="between"><span>本周复习</span><strong>{done} / {target} 分钟</strong></div><Progress value={Math.min(100,done/target*100)} aria-label={c.name+"本周复习进度"} className="course-progress"/><div className="course-meta"><span>{s.gaps.filter(g=>g.courseId===c.id&&g.status!=="resolved").length} 个未关闭点</span><span>权重 {c.weight}/5</span><span>{c.examDate?(daysUntil(c.examDate,date)>=0?"距考试 "+daysUntil(c.examDate,date)+" 天":"考试日期已过"):"考试待定"}</span></div><div className="actions"><button className="btn soft small" onClick={()=>open({kind:"class",id:c.id})}>记录课堂</button><button className="btn ghost small" onClick={()=>open({kind:"review",id:c.id})}>开始周复习</button></div></article>})}</div>}
 <div className="section-title section-gap"><h2>课堂与课后关闭</h2><span>模式可以随时切换</span></div>
 {s.sessions.filter(x=>x.status!=="closed").length===0?<div className="quiet-empty">没有待关闭的课堂。上完一节核心课后，在这里留下线索。</div>:s.sessions.filter(x=>x.status!=="closed").slice().reverse().map(c=><article className="session-card" key={c.id}><div className="section-title"><div><h3>{cname(c.courseId)} · {c.topic}</h3><p>{c.date} · {c.status==="brief"?"简版已记录，等待周复习补全":"待课后关闭"}</p></div><button className="btn soft small" onClick={()=>open({kind:"closure",id:c.id})}>课后关闭 <ChevronRight size={16}/></button></div><Tabs value={c.mode} onValueChange={v=>void edit(n=>{const cl=n.sessions.find(x=>x.id===c.id)!;cl.mode=v as "A"|"B"|"C";cl.modeEvents.push({mode:cl.mode,at:new Date().toISOString()})},"课堂模式已切换")}><TabsList className="class-tabs">{(["A","B","C"] as const).map(m=><TabsTrigger key={m} value={m}>{m} · {classNames[m]}</TabsTrigger>)}</TabsList></Tabs><div className="class-instruction"><span>{classInstructions[c.mode]}</span><button className="text-link" onClick={()=>open({kind:"gap",type:c.courseId})}>记一个卡点</button></div></article>)}
 <div className="section-title section-gap"><h2>问题池</h2><button className="btn ghost small" disabled={!s.courses.length} onClick={()=>open({kind:"gap"})}><Plus size={15}/>记问题</button></div>{s.gaps.filter(g=>g.status!=="resolved").length===0?<div className="quiet-empty">暂时没有未关闭知识点。</div>:<div className="gap-list">{s.gaps.filter(g=>g.status!=="resolved").sort((a,b)=>Number(b.risk==="high")-Number(a.risk==="high")).map(g=><button className="gap-row" key={g.id} onClick={()=>open({kind:"gap",id:g.id})}><span className={"risk-bar "+g.risk}/><div><strong>{g.question}</strong><small>{cname(g.courseId)} · {g.status==="exam"?"留到考前":g.risk==="high"?"优先处理":"本周处理"}</small></div><ChevronRight size={17}/></button>)}</div>}
 <details className="history"><summary>查看已关闭课堂、已解决问题与复习记录</summary>{s.sessions.filter(x=>x.status==="closed").map(c=><div className="record" key={c.id}><strong>{cname(c.courseId)} · {c.topic}</strong><p>{c.summary}</p><p>我会：{c.canExplain}</p></div>)}{s.gaps.filter(g=>g.status==="resolved").map(g=><button className="gap-row" key={g.id} onClick={()=>open({kind:"gap",id:g.id})}><Check size={16}/><span>{g.question}</span></button>)}{s.reviews.slice().reverse().map(r=><div className="record" key={r.id}><strong>{cname(r.courseId)} · {r.date} · {r.minutes} 分钟</strong><p>框架：{r.framework||"未记录"}</p><p>问题：{r.problems||"未记录"}</p><p>闭卷回忆：{r.recall||"未记录"}</p><p>长期记忆：{r.memory||"未记录"}</p></div>)}</details>
 </TabsContent>
 <TabsContent value="coach"><CoachPanel data={s} demo={demo} saving={saving} edit={edit} onExplain={setExplain} onGoToday={()=>setTab("today")}/></TabsContent>
 <TabsContent value="library"><LibraryPanel data={s} demo={demo} saving={saving} edit={edit} onExplain={setExplain} onGoCourses={()=>setTab("courses")} onStartOwn={startOwn}/></TabsContent>
 <TabsContent value="assignments"><div className="section-title"><h2>待提交作业</h2><button className="btn" onClick={()=>open({kind:"assignment"})}><Plus size={16}/>添加作业</button></div><div className="grade-guide"><div><b>A</b><strong>高学习价值</strong><span>认真做，卡点回流课程</span></div><div><b>B</b><strong>必交低价值</strong><span>合格完整，适度投入</span></div><div><b>C</b><strong>机械任务</strong><span>碎片处理，批量完成</span></div></div>
 {s.assignments.filter(a=>a.status==="open").length===0?<EmptyBox title="没有待交作业" description="新作业出现时，先确定截止时间和最低合格标准。"/>:s.assignments.filter(a=>a.status==="open").sort((a,b)=>a.due.localeCompare(b.due)).map(a=><article className="assignment-row" key={a.id}><span className={"grade grade-"+a.grade}>{a.grade}</span><div className="assignment-body"><div className="between"><h3>{a.title}</h3><span className={daysUntil(a.due,date)<=1?"deadline urgent":"deadline"}>{a.due} 截止</span></div><p>{a.minimum||"尚未填写最低合格标准"}</p><div className="course-meta"><span>{cname(a.courseId)}</span><span>已投入 {a.spent} / 预计 {a.estimate} 分钟</span><span>每次上限 {a.cap} 分钟</span>{a.blockedBy.length>0&&<span className="text-warn">等「{a.blockedBy.map(id=>s.assignments.find(x=>x.id===id)?.title??"前置作业").join("、")}」先完成</span>}</div>{a.spent>=a.estimate&&<p className="text-warn">实际投入已达到预计总时长，请重新判断提交范围。</p>}<div className="actions"><button className="btn soft small" onClick={()=>open({kind:"worklog",id:a.id})}>记录进度 / 提交</button><button className="btn ghost small" onClick={()=>open({kind:"assignment",id:a.id})}>调整</button></div></div></article>)}
 <details className="history"><summary>已提交 {s.assignments.filter(a=>a.status==="done").length} 份</summary>{s.assignments.filter(a=>a.status==="done").map(a=><div className="between record" key={a.id}><span><Check size={16}/> {a.title}</span><button className="text-link" onClick={()=>void edit(n=>{n.assignments.find(x=>x.id===a.id)!.status="open";putDay(n).completed=putDay(n).completed.filter(x=>x!=="assignment:"+a.id)},"已恢复为待提交")}>撤销提交标记</button></div>)}</details>
 </TabsContent>
 <TabsContent value="life"><div className="section-title"><h2>先守住生活底线</h2><button className="btn ghost" onClick={()=>open({kind:"settings"})}><Settings2 size={16}/>调整底线</button></div><div className="life-grid"><article className="life-card"><Moon size={24}/><span>睡眠</span><strong>{day.sleepRecorded?day.sleep:"—"}<small> / {s.settings.sleepFloor} 小时</small></strong><p>{!day.sleepRecorded?"请先记录昨晚睡眠":day.sleep>=s.settings.sleepFloor?"昨晚达到了个人底线":"今天优先降低负荷"}</p><button className="text-link" onClick={()=>open({kind:"day"})}>更新昨晚睡眠</button></article><article className="life-card"><Activity size={24}/><span>运动</span><strong>{lifeCount("exercise")}<small> / {s.settings.exerciseTarget} 天</small></strong><p>每周累计，允许灵活安排。</p><button className="text-link" onClick={()=>open({kind:"life",type:"exercise"})}>记录一次运动</button></article><article className="life-card"><Heart size={24}/><span>社交</span><strong>{lifeCount("social")}<small> / {s.settings.socialTarget} 天</small></strong><p>留时间给在意的人。</p><button className="text-link" onClick={()=>open({kind:"life",type:"social"})}>记录一次相处</button></article><article className="life-card"><Pause size={24}/><span>休息</span><strong>{s.life.filter(x=>x.date===date&&x.type==="rest").reduce((n,x)=>n+x.minutes,0)}<small> / {s.settings.restMinutes} 分钟</small></strong><p>不必等任务全部清空。</p><button className="text-link" onClick={()=>open({kind:"life",type:"rest"})}>记录一段休息</button></article></div>
 <div className="section-title section-gap"><div><h2>发展方向</h2><p className="muted">1 个主方向 + 1 个维护方向，其余暂停保留。</p></div><button className="btn" onClick={()=>open({kind:"track"})}><Plus size={16}/>添加方向</button></div>{rec.mode!=="normal"&&<div className="notice">本周发展事项默认降级。只有临近硬截止的事项继续进入今日推荐。</div>}{!s.tracks.length?<EmptyBox title="让一两个方向慢慢前进" description="英语、赚钱和项目不必每天全部推进。"/>:<div className="track-grid">{s.tracks.map(t=><article className={"track-card "+(t.role==="paused"?"paused":"")} key={t.id}><div className="between"><h3>{t.name}</h3><span className="pill">{t.role==="main"?"主方向":t.role==="maintain"?"维护方向":"已暂停"}</span></div><p>{t.next}</p><div className="between"><span>本周 {s.life.filter(x=>x.type==="development"&&x.trackId===t.id&&weekOf(x.date)===wk).length} / {t.weeklyTarget} 次</span><span>{t.minutes} 分钟 / 次</span></div><div className="actions"><button className="btn soft small" onClick={()=>open({kind:"life",type:"development",id:t.id})}>记录推进</button><button className="btn ghost small" onClick={()=>open({kind:"track",id:t.id})}>调整角色</button></div></article>)}</div>}
 <details className="history"><summary>本周生活与发展记录</summary>{s.life.filter(x=>weekOf(x.date)===wk).slice().reverse().map(l=><div className="between record" key={l.id}><span>{l.date} · {l.type==="rest"?"休息":l.type==="exercise"?"运动":l.type==="social"?"社交":s.tracks.find(t=>t.id===l.trackId)?.name??"发展"}</span><span>{l.minutes} 分钟</span></div>)}</details></TabsContent>
 <TabsContent value="week"><div className="week-header"><div><span className="eyebrow">{wk} — {addDays(wk,6)}</span><h2>{week.reviewed?"这一周已经复盘过了":"不看忙了多久，看哪些地方需要调整。"}</h2><p>下周只优先解决一个最大的阻力。</p></div><button className="btn" onClick={()=>open({kind:"reflection"})}>{week.reviewed?"查看 / 更新复盘":"开始本周复盘"}<ArrowUpRight size={16}/></button></div><div className="week-stats"><div><span>单科复习</span><strong>{weekMinutes}<small> 分钟</small></strong></div><div><span>未关闭知识点</span><strong>{s.gaps.filter(g=>g.status!=="resolved").length}<small> 个</small></strong></div><div><span>达到睡眠底线</span><strong>{weekDays.filter(d=>s.days[d]?.sleepRecorded&&s.days[d].sleep>=s.settings.sleepFloor).length}<small> 天 / 已记录 {weekDays.filter(d=>s.days[d]?.sleepRecorded).length} 天</small></strong></div><div><span>反复跳过</span><strong>{weekDays.reduce((n,d)=>n+(s.days[d]?.skips.length??0),0)}<small> 次</small></strong></div></div>
 <div className="dashboard-grid"><section className="panel"><div className="section-title"><h2>核心课复习额度</h2><span>{modeNames[rec.mode]}</span></div>{s.courses.filter(c=>c.core).map(c=>{const done=reviewDone(s,c.id,date),target=courseTarget(s,c,date);return <div className="budget-row" key={c.id}><div className="between"><strong>{c.name}</strong><span>{done} / {target} 分钟</span></div><Progress value={Math.min(100,done/target*100)} aria-label={c.name+"复习额度"}/><div className="between"><span>{done>=target?"本周额度已达成":"还需 "+(target-done)+" 分钟"}</span><button className="text-link" onClick={()=>open({kind:"course",id:c.id})}>调整额度</button></div></div>})}{!s.courses.some(c=>c.core)&&<p>添加核心课后，在这里预留每周复习额度。</p>}<div className="rule-line"/><div className="between"><span>本周待投入估计</span><strong>{getMode(s,date).load} / {s.settings.weeklyCapacity} 分钟</strong></div><p>包括核心课剩余原始额度和 7 天内到期作业，不含课表、固定生活安排与发展事项。</p></section><aside><section className="note-panel"><span className="eyebrow">忙的时候，按顺序缩减</span><ol className="downgrade"><li>取消美化与重复整理</li><li>暂停次要发展方向</li><li>B / C 作业做到合格</li><li>复习保留回忆与关键问题</li><li>课后关闭改为 2 分钟</li></ol><p>仍然超载时，主动协调截止与目标，守住睡眠和基本生活。</p></section></aside></div>
 <div className="section-title section-gap"><h2>积压校准</h2><span>保留、缩小或明确延后</span></div>{s.sessions.some(c=>c.status!=="closed"&&c.date<wk)?s.sessions.filter(c=>c.status!=="closed"&&c.date<wk).map(c=><div className="simple-row" key={c.id}><div><h3>{cname(c.courseId)} · {c.topic}</h3><p>{c.date} · 先提取高风险卡点，再关闭旧记录。</p></div><button className="btn ghost small" onClick={()=>open({kind:"closure",id:c.id})}>压缩并关闭</button></div>):<div className="quiet-empty">没有跨周未关闭的课堂。知识点可到问题池逐项调整去向。</div>}
 {week.reviewed&&<section className="panel section-gap"><h3>本周复盘记录</h3><p className="preserve">{week.reflection}</p><div className="rule-line"/><h3>下周调整</h3><p className="preserve">{week.adjustment}</p><p>下周模式：{s.weeks[addDays(wk,7)]?.mode==="auto"?"自动判断":modeNames[s.weeks[addDays(wk,7)]?.mode as Mode]??"自动判断"}</p><p>最大风险：{s.weeks[addDays(wk,7)]?.risk||"未填写"}</p></section>}
 <details className="history"><summary>过去的周复盘</summary>{Object.entries(s.weeks).filter(([w,v])=>w<wk&&v.reviewed).sort(([a],[b])=>b.localeCompare(a)).map(([w,v])=><div className="record" key={w}><strong>{w} 这一周</strong><p className="preserve">{v.reflection}</p><p className="preserve">{v.adjustment}</p></div>)}</details>
 </TabsContent></Tabs>
 <nav className="mobile-nav" aria-label="手机页面导航">{mobileNav.map(({id,label,Icon})=><button type="button" key={id} aria-current={tab===id?"page":undefined} onClick={()=>setTab(id)}><Icon size={20}/><span>{label}</span></button>)}<details className="mobile-nav-more"><summary aria-label="更多页面" aria-current={mobileMoreNav.some(([id])=>id===tab)?"page":undefined}><MoreHorizontal size={20}/><span>更多</span></summary><div className="mobile-more-menu">{mobileMoreNav.map(([id,label])=><button type="button" key={id} onClick={e=>{setTab(id);e.currentTarget.closest("details")?.removeAttribute("open")}}>{label}<ChevronRight size={16}/></button>)}</div></details></nav>
 </main><footer>余量 · 按周平衡，按天执行。<span>第一版 / 01</span></footer>
 <Dialog open={!!modal} onOpenChange={v=>{if(!v&&!saving)setModal(null)}}><DialogContent className="balance-dialog"><DialogHeader><DialogTitle>{modalTitle}</DialogTitle><DialogDescription>{description}</DialogDescription></DialogHeader><form onSubmit={submit}>{currentFields}<div className="dialog-actions"><button className="btn ghost" type="button" disabled={saving} onClick={()=>setModal(null)}>取消</button><button className="btn" type="submit" disabled={saving}>{saving?"保存中…":submitLabel}</button></div></form></DialogContent></Dialog>
 <ExplainDialog seed={explain} onClose={()=>setExplain(null)}/>
 </>;
}
