import { sqliteTable,text,integer,real,index } from "drizzle-orm/sqlite-core";
export const balanceState=sqliteTable("balance_state",{userId:text("user_id").primaryKey(),payload:text("payload").notNull(),revision:integer("revision").notNull(),updatedAt:text("updated_at").notNull()});
export const materials=sqliteTable("materials",{id:text("id").primaryKey(),userId:text("user_id").notNull(),courseId:text("course_id").notNull(),name:text("name").notNull(),kind:text("kind").notNull(),location:text("location").notNull(),filename:text("filename").notNull(),contentType:text("content_type").notNull(),size:integer("size").notNull(),storageKey:text("storage_key").notNull(),url:text("url").notNull(),createdAt:text("created_at").notNull()});
// 资料解析任务。parse_status 与 generate_status 分开保存：上传、解析、出题是三个独立状态，不能互相代替。
export const materialTasks=sqliteTable("material_tasks",{id:text("id").primaryKey(),userId:text("user_id").notNull(),materialId:text("material_id").notNull(),courseId:text("course_id").notNull(),parseStatus:text("parse_status").notNull(),parseEngine:text("parse_engine").notNull().default(""),parseError:text("parse_error").notNull().default(""),parseAttempts:integer("parse_attempts").notNull().default(0),parseCursor:integer("parse_cursor").notNull().default(0),generateStatus:text("generate_status").notNull(),generateEngine:text("generate_engine").notNull().default(""),generateError:text("generate_error").notNull().default(""),generateAttempts:integer("generate_attempts").notNull().default(0),generateCursor:integer("generate_cursor").notNull().default(0),sourceSha256:text("source_sha256").notNull().default(""),byteSize:integer("byte_size").notNull().default(0),pageCount:integer("page_count").notNull().default(0),blockCount:integer("block_count").notNull().default(0),truncated:integer("truncated").notNull().default(0),leaseUntil:text("lease_until").notNull().default(""),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()},(t)=>[index("material_tasks_user_material_idx").on(t.userId,t.materialId,t.createdAt)]);
// 解析出的文本块，保留原文位置用于展示来源。
export const materialBlocks=sqliteTable("material_blocks",{id:text("id").primaryKey(),taskId:text("task_id").notNull(),userId:text("user_id").notNull(),materialId:text("material_id").notNull(),courseId:text("course_id").notNull(),ordinal:integer("ordinal").notNull(),locator:text("locator").notNull(),locatorKind:text("locator_kind").notNull(),locatorValue:integer("locator_value").notNull().default(0),heading:text("heading").notNull().default(""),text:text("text").notNull(),charCount:integer("char_count").notNull().default(0)},(t)=>[index("material_blocks_task_ordinal_idx").on(t.taskId,t.ordinal)]);
// 候选知识点。用户确认后才写入 state.knowledgePoints。
export const materialKnowledgePoints=sqliteTable("material_knowledge_points",{id:text("id").primaryKey(),taskId:text("task_id").notNull(),userId:text("user_id").notNull(),materialId:text("material_id").notNull(),courseId:text("course_id").notNull(),label:text("label").notNull(),detail:text("detail").notNull().default(""),confidence:real("confidence").notNull().default(0),origin:text("origin").notNull(),locator:text("locator").notNull().default(""),locatorKind:text("locator_kind").notNull().default(""),locatorValue:integer("locator_value").notNull().default(0),sourceBlockId:text("source_block_id").notNull().default(""),status:text("status").notNull(),createdAt:text("created_at").notNull()},(t)=>[index("material_knowledge_points_task_status_idx").on(t.userId,t.taskId,t.status)]);
// 候选题。未经用户确认不得进入正式题库。
export const materialCandidates=sqliteTable("material_candidates",{id:text("id").primaryKey(),taskId:text("task_id").notNull(),userId:text("user_id").notNull(),materialId:text("material_id").notNull(),courseId:text("course_id").notNull(),knowledgePointId:text("knowledge_point_id").notNull().default(""),prompt:text("prompt").notNull(),options:text("options").notNull(),correctIndex:integer("correct_index").notNull(),explanation:text("explanation").notNull().default(""),source:text("source").notNull().default(""),locatorKind:text("locator_kind").notNull().default(""),locatorValue:integer("locator_value").notNull().default(0),origin:text("origin").notNull(),status:text("status").notNull(),edited:integer("edited").notNull().default(0),questionId:text("question_id").notNull().default(""),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()},(t)=>[index("material_candidates_task_status_idx").on(t.userId,t.taskId,t.status)]);
